### ISSUE TITLE
Configuring the Daemon

### ISSUE THREAD

**Issue by kittylyst** [newrelic/newrelic-jfr-core#36]
## Summary

Need to give the option to configure basic operating parameters for the daemon.

## Desired Behaviour

* Use of socket or filesystem for the JFR recording
* Port number for JMX (default 1099)
* Hostname to connect to (default localhost)
* Sending app name (currently default to reading from env var)
* Version number of daemon / mappers (need for when we need to hassle internal early adopters to upgrade)

## Additional context

How should these be specified? -D config vars or something else?

**Comment by breedx-nr** [comment]
Here is my suggested path forward, point by point, but taking remote service name (the name of the monitored application) first since it's most complicated:

### app name
**proposal**: a daemon-local env var `NEW_RELIC_APP_NAME` will be used.  If specified, this will override any remote system property.  If the daemon-local env var `NEW_RELIC_APP_NAME` is not specified, then a remote system property named `nr.service.name` will be checked and used.  If that system property is not found, we will log a loud warning and default the service name to `jfr_hobgoblin`.

### remote jmx port
default to 1099, but may be overridden by daemon env var named `REMOTE_JMX_PORT`.

### remote jmx host
default to `localhost`, but may be overridden by daemon env var named `REMOTE_JMX_HOST`

### daemon version number
read the version number from the jar file manifest

### strategy to get data (shared file or stream over jmx)
**proposal** Default to streaming over JMX, with a daemon env var called `JFR_SHARED_FILESYSTEM` which can be the value `true` (use a shared filesystem) or `false` (stream over jmx).

Thoughts?
---
Down the road, we should give some consideration to JMX over TLS.
