### ISSUE TITLE
Allow environment variable to enable sdk audit mode logging

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-jfr-core#91]
It could be very useful to specify an environment variable that would enable audit mode (verbose logging) in the underlying sdk.  

Details about how audit mode is configured [are here in the sdk repo](https://github.com/newrelic/newrelic-telemetry-sdk-java#enabling-audit-logging).
Perhaps when the TelemetryClient is created this can also be configured.

**Comment by XiXiaPdx** [comment]
Assuming verbose logging means debug level for the underlying sdk, I got it to work by following convention with a custom logging configuration file.  

``` 
java -Dlog4j.configurationFile=log4j2.xml -jar  jfr-daemon-0.6.0-SNAPSHOT.jar `
```

@breedx-nr  I am double checking you would rather enable it programmatically via an environment variable?

<img width="1632" alt="Screen Shot 2020-10-12 at 8 53 44 AM" src="https://user-images.githubusercontent.com/24482401/95767075-0a5e8c80-0c69-11eb-8371-4e8c45e130f3.png">

**Comment by breedx-nr** [comment]
I updated the description with some info on what I had expected.

**Comment by XiXiaPdx** [comment]
Currently, when a Telemetry SDK Metric or Event Batch Sender is built in the `TelemetryClientFactory`,  audit mode is already hardcoded to true. 

https://github.com/newrelic/newrelic-jfr-core/blob/56837cda29485aedc0e95e073fd9edffffd56b0a/jfr-daemon/src/main/java/com/newrelic/jfr/daemon/TelemetryClientFactory.java#L38

Although it is true, there are no debug logs right now. I think that's because the jfr-daemon jar is built with a default `log4j2.xml` that configures logging and sets it at `Info` level. 

https://github.com/newrelic/newrelic-jfr-core/blob/e29aa68578670e4edb82804a07c8fb8d6f5924b2/jfr-daemon/src/main/resources/log4j2.xml#L12

Let me know if I'm reasoning is off. Thanks!

**Comment by breedx-nr** [comment]
I think you're on track.  I would add that we should probably NOT hard code audit mode to `true`, but instead base it on this new environment variable.

If the log4j2.xml file included with the daemon is limiting our ability to use audit mode in the sdk, then we should probably rework that as well.
